### ISSUE TITLE
[Listing] onClick should use specified id instead of hardcoded `data.id`

### ISSUE THREAD

**Issue by opera-robertz** [react-backoffice/backoffice#27]
Hi, first of all, nice library! 

When looking into different libraries for building an backoffice I found this one, which looks very promising. I have one possible improvement regarding the implementation in `Cell`
https://github.com/react-backoffice/backoffice/blob/94a155e75236c4a4a9bab934290c4a98548747b4/src/Listing/ListingLine.tsx#L60

Here, perhaps it would be better to use the value specified in Listing prop `id`. 

Here is a quick [codesandbox](https://codesandbox.io/s/relaxed-beaver-of5le?file=/src/App.js) that I created which made me find this unexpected behaviour, if the key is not explicitly `id`, onClick will always be called with `undefined`.

Although, I understand that it is possible to map dataList to create a field id, which makes this rather low priority. But perhaps the addition to the docs could indicate that key `.id` is being used and that [this](https://github.com/react-backoffice/backoffice#listing) might be misleading:

```
data: any[]
```

When id is very important for component to work.

I could perhaps look into this if it is desirable, as I considered creating a patchfile for it.

For achieving my desired behaviour, it is simple enough to change the line to be:
```javascript
onClick={() => onClick && onClick(data)}
```

Happy Coding ⌨️

**Comment by drublic** [comment]
Hi Robert, thanks for the feedback.
Makes a lot of sense from my understanding.
Please open a PR if you find the time and I will make sure to merge it soon.
